env: "uat"

app:
  port: "2255"
  url: "https://uat-pos-system.co.th"
  base_url: 

pg:
  host: "aws-1-ap-southeast-2.pooler.supabase.com"
  port: "5432"
  name: "postgres"
  username: "postgres.lfuooeyylufmbqwgtkot"
  password: "uVvmKxFInjvv5Zng"

supabase:
  url: "https://lfuooeyylufmbqwgtkot.supabase.co"
  service_role_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmdW9vZXl5bHVmbWJxd2d0a290Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTY5NjcxNywiZXhwIjoyMDg1MjcyNzE3fQ.ZldQo67n0zhao0qpOOTB97c8snjxOXQbx42Qk_oA9qE"
  bucket: "pos-file-uat"